version: '3.8'
services:
  webapp:
    image: com.example/webapp
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: -Dfile.encoding=UTF-8 -Duser.language=ja -Duser.country=JP
      SERVER_PORT: 8080
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432,db:5432/postgres?loginTimeout=2&connectTimeout=2&cancelSignalTimeout=2&socketTimeout=60&tcpKeepAlive=true&targetServerType=primary&loadBalanceHosts=true
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
  batch:
    image: com.example/batch
    depends_on:
      - webapp
      - db
    environment:
      JAVA_OPTS: -Dfile.encoding=UTF-8 -Duser.language=ja -Duser.country=JP
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432,db:5432/postgres?loginTimeout=2&connectTimeout=2&cancelSignalTimeout=2&socketTimeout=60&tcpKeepAlive=true&targetServerType=primary&loadBalanceHosts=true
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
  db:
    image: postgres:12.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
