spring.config:
  activate.on-profile: test
logging.level:
  org.springframework: DEBUG
  org.jooq: DEBUG
  org.flyway: DEBUG
  com.example: DEBUG
spring.datasource:
  driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  url: jdbc:tc:postgresql:12.4-alpine:///db
